### ISSUE TITLE
add isNonNullString helper method

### ISSUE THREAD

**Issue by rreinold** [yashjain28/gcloud-bigquery#10]
remove dup

**Comment by yashjain28** [comment]
function isInvalidString(str){
            return (!str || (typeof str != 'string') || str.length==0);
} //adding this because I am checking 3 things and not just not null, let me know if that sounds correct.

**Comment by rreinold** [comment]
https://jsfiddle.net/9tqzbsmt/3/

**Comment by yashjain28** [comment]
Done
