### ISSUE TITLE
modify callback

### ISSUE THREAD

**Issue by rreinold** [yashjain28/gcloud-bigquery#5]
built-in clearblade library's callback signatures are

/**
 * @param {boolean} err
 * @param {Object} data
 */
function callback(err, data) {}

but built-in http library callback is 
/**
 * @param {boolean | Object} err
 * @param {Object | null} data
 */
function callback(err, data){}

I recommend adapting the http's callback signature to better align with clearblade library's

**Comment by yashjain28** [comment]
Need to talk about this!

**Comment by rreinold** [comment]
i take back this comment, not plausible
