### ISSUE TITLE
object declaration too verbose

### ISSUE THREAD

**Issue by rreinold** [yashjain28/gcloud-bigquery#6]
var options = {
        "authToken": authToken,
        "projectID": projectID
    }

**Comment by yashjain28** [comment]
I am sorry but I didn't get this!

**Comment by rreinold** [comment]
531b66719ea418bfcfd21a407cfb79ef8c162e48

**Comment by yashjain28** [comment]
29bce9ea027c0571f6d356f767e7480f3512f7b9

Removed this as it is no longer required. Never used the options object in the code.
