### ISSUE TITLE
Optional - cleaner URL creation

### ISSUE THREAD

**Issue by rreinold** [yashjain28/gcloud-bigquery#7]
const BASE_URL = "https://www.googleapis.com/bigquery/v2";
    const PROJECT_URL = [BASE_URL,'projects'].join('/')
.. and so on
...
    const DATASET_URL = [BASE_UR, projectID, 'datasets'].join('/')

**Comment by yashjain28** [comment]
_joinWithSlash(DATASET_URL, datasetID); => DATASET_URL/datasetID

function _joinWithSlash(){ // can have any number of arguments 
        return Array.from(arguments).join('/');
 }
Let me know if this works

**Comment by rreinold** [comment]
i dont see a need to add a function with one line body

**Comment by rreinold** [comment]
531b66719ea418bfcfd21a407cfb79ef8c162e48
